# Generated by cucumber-sinatra. (2014-02-07 14:20:28 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Sculpt

class SculptWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SculptWorld.new
end


Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end

# WebDriver driver = new RemoteWebDriver("http://localhost:9515", DesiredCapabilities.chrome());
# driver.get("http://www.google.com");



